### ISSUE TITLE
The Mac bot doesn't get currently online players when launched

### ISSUE THREAD

**Issue by Bibliofile** [Blockheads-Messagebot/MessageBot#41]
When first launched, the portal bot uses the overview tab of the portal (http://portal.theblockheads.net/worlds/WORLDID) to fetch the currently online players list, this is not available to mac servers and thus a replacement needs to be found. One solution may be scraping the GUI but if there is another way that is less messy it would be highly desirable.

**Comment by dapersonmgn** [comment]
At startup get the logs and see which players are connected via join/leave msgs? And listen to that?

**Comment by Bibliofile** [comment]
This has been fixed now that the bot uses `blockheads-api`.
