### ISSUE TITLE
buildTemplate - select value not showing

### ISSUE THREAD

**Issue by dapersonmgn** [Blockheads-Messagebot/MessageBot#52]
**Before reporting an issue please make sure the following boxes are checked:**

## For the browser based bot:
- [x] Reproducible in a recent browser (browser usage > 1.5% as reported by [caniuse.com](http://caniuse.com/#feat=calc) and *not* Opera Mini)
- [x] Not an issue with an extension (report in the correct repo)

Also please fill in the following information:
Your browser: Chrome 59.0.3071.115
Steps to reproduce: Add a select tag as a selector in the values argument and change the value. (the attributes to change. Not sure what quite to name it.) 

```
ui.buildTemplate(tab.querySelector("template"),tab.querySelector(".columns"),[      {
        selector: "textarea",
        value: "whoa. A PVP msg.",
      },
      {
        selector: "select[data-input=\"whoVictim\"]",
        value: "admin"
      },
      {
        selector: "select[data-input=\"whoAttacked\"]",
        value: "mod"
      }]);
```
my example.

**Comment by Bibliofile** [comment]
I believe this has been fixed in the Framework branch (working on merging to master) but I haven't tested it yet.
